// Generated by CoffeeScript 1.6.3
(function() {
  var mandel, mandelzahl, print;

  print = console.log;

  mandelzahl = function(cx, cy, max) {
    var i, tx, zx, zy;
    zx = 0.0;
    zy = 0.0;
    i = 0;
    while (++i <= max && (zx * zx + zy * zy) < 4) {
      tx = zx * zx - zy * zy + cx;
      zy = zx * zy * 2 + cy;
      zx = tx;
    }
    if (i > max) {
      return -1;
    } else {
      return i;
    }
  };

  mandel = function(w, h, max) {
    var mz, sb, x, y, _i, _j, _ref, _ref1, _results;
    y = -1.0;
    _results = [];
    for (y = _i = -1.0, _ref = 2.0 / h; _ref > 0 ? _i <= 1.0 : _i >= 1.0; y = _i += _ref) {
      sb = "";
      for (x = _j = -2.0, _ref1 = 3.0 / w; _ref1 > 0 ? _j <= 1.0 : _j >= 1.0; x = _j += _ref1) {
        mz = mandelzahl(x, y, max);
        if (mz > 0) {
          sb = sb + '-';
        } else {
          sb = sb + '*';
        }
      }
      _results.push(print(sb));
    }
    return _results;
  };

  mandel(140, 50, 10000);

}).call(this);
